# Site settings
title: Boulevardier
email: kirschbombe@gmail.com
description: "Jekyll theme for maps and text"
baseurl: "/boulevardier-jekyll/" # the subpath of your site, e.g. /blog/
url: "http://dawnchildress.com/boulevardier-jekyll/" # the base hostname & protocol for your site
twitter_username: kirschbombe
github_username:  kirschbombe

# Build settings
markdown: kramdown

# Map
map-tileset: 'http://{s}.tile.stamen.com/toner-lite/{z}/{x}/{y}.png'
map-credits: '<a target="_blank" href="https://github.com/svmatthews/jekyll-maps">Jekyll Maps</a> | Tiles: Stamen & OSM'
